[tool.ruff]
line-length = 120
target-version = "py311"
src = ["scrapping"]

[tool.ruff.lint]
preview = true
extend-select = [
    'E', 'F', 'W', 'C90', 'A', 'ANN', 'S', 'B', 'PT', 'Q', 'RSE', 'SIM', 'ARG', 'PTH', 'PD',
    'TRY', 'FLY', 'NPY', 'PLC', 'PLE', 'PLW', 'I',
    ]


[tool.sqlfmt]
dialect = "polyglot"
line_length = 120
exclude=[
    "./transform/nba_dwh/target/**/*",
    "./transform/nba_dwh/dbt_packages/**/*",
    "./venv/**/*",
    ]
