
version: 2

models:
  - name: game_boxscore
    description: "Boxscore of nba games"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: game_id
        tests:
          - not_null
          - relationships:
              to: ref('game')
              field: id
      - name: team_id
        tests:
          - not_null
          - relationships:
              to: ref('team')
              field: id
      - name: player_id
        tests:
          - not_null
          - relationships:
              to: ref('player')
              field: id
      - name: field_goals_pct
        description: "Conversion rate on field goals"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1

  - name: player_season
    description: "Players stats currently only regular season"
    columns:
      - name: id
        description: "Player stats id (hash of name, season year and team)"
        tests:
          - not_null
          - unique
      - name: player_id
        tests:
          - not_null
          - relationships:
              to: ref('player')
              field: id
      - name: team_id
        tests:
          - not_null
          - relationships:
              to: ref('team')
              field: id
      - name: season_id
        tests:
          - not_null
          - relationships:
              to: ref('season')
              field: id
      - name: nb_games
        description: "Number of games played on the season"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0

  - name: game_summary
    description: "Basic summary of NBA games"
    columns:
      - name: id
        description: "Primary key of the table"
        tests:
          - not_null
          - unique
      - name: home_team_id
        description: "ID (name) of the team playing at home"
        tests:
          - relationships:
              to: ref('team_season')
              field: team_id
      - name: away_team_id
        description: "ID (name) of the team playing away"
        tests:
          - relationships:
              to: ref('team_season')
              field: team_id

  - name: team_season
    description: "Summary of every season per NBA team"
    columns:
      - name: id
        description: "Primary key of the table"
        tests:
          - not_null
          - unique
      - name: team_id
        tests:
          - not_null
          - relationships:
              to: ref('team')
              field: id
      - name: season_id
        tests:
          - not_null
          - relationships:
              to: ref('season')
              field: id

  - name: team
    description: "Every NBA teams"
    columns:
      - name: id
        description: "Primary key of the table"
        tests:
          - not_null
          - unique

  - name: season
    description: "Dates of every seasons"
    columns:
      - name: id
        test:
          - not_null
          - unique

  - name: player
    description: "Every players who played in an NBA game"
    columns:
      - name: id
        test:
          - not_null
          - unique


sources:
  - name: local_source
    config:
      external_location: "./local_source/{name}.{extension}"
    tables:
      - name: game_boxscore_1999
        description : 'boxscore table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_boxscore_2000
        description : 'boxscore table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_boxscore_2001
        description : 'boxscore table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_boxscore_2002
        description : 'boxscore table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_boxscore_2003
        description : 'boxscore table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_boxscore_2004
        description : 'boxscore table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_boxscore_2005
        description : 'boxscore table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_boxscore_2006
        description : 'boxscore table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_boxscore_2007
        description : 'boxscore table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_boxscore_2008
        description : 'boxscore table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_boxscore_2009
        description : 'boxscore table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_boxscore_2010
        description : 'boxscore table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_boxscore_2011
        description : 'boxscore table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_boxscore_2012
        description : 'boxscore table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_boxscore_2013
        description : 'boxscore table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_boxscore_2014
        description : 'boxscore table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_boxscore_2015
        description : 'boxscore table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_boxscore_2016
        description : 'boxscore table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_boxscore_2017
        description : 'boxscore table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_boxscore_2018
        description : 'boxscore table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_boxscore_2019
        description : 'boxscore table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_boxscore_2020
        description : 'boxscore table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_boxscore_2021
        description : 'boxscore table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_boxscore_2022
        description : 'boxscore table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_boxscore_2023
        description : 'boxscore table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_boxscore_2024
        description : 'boxscore table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_schedule_1999
        description : 'schedule table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_schedule_2000
        description : 'schedule table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_schedule_2001
        description : 'schedule table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_schedule_2002
        description : 'schedule table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_schedule_2003
        description : 'schedule table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_schedule_2004
        description : 'schedule table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_schedule_2005
        description : 'schedule table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_schedule_2006
        description : 'schedule table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_schedule_2007
        description : 'schedule table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_schedule_2008
        description : 'schedule table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_schedule_2009
        description : 'schedule table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_schedule_2010
        description : 'schedule table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_schedule_2011
        description : 'schedule table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_schedule_2012
        description : 'schedule table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_schedule_2013
        description : 'schedule table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_schedule_2014
        description : 'schedule table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_schedule_2015
        description : 'schedule table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_schedule_2016
        description : 'schedule table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_schedule_2017
        description : 'schedule table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_schedule_2018
        description : 'schedule table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_schedule_2019
        description : 'schedule table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_schedule_2020
        description : 'schedule table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_schedule_2021
        description : 'schedule table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_schedule_2022
        description : 'schedule table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_schedule_2023
        description : 'schedule table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet
      - name: game_schedule_2024
        description : 'schedule table for a given season'
        tags: ['sources_concat']
        meta:
            extension: parquet


      - name: season_calendar
        description: "Start and end date of seasons"
        meta:
          extension: csv
