
version: 2

models:
  - name: game_boxscore
    description: "Boxscore of nba games"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: game_id
        description: "Id of the modeled game"
        tests:
          - not_null
      - name: field_goals_pct
        description: "% of conversion on field goals"

  - name: player
    description: "Players stats"
    columns:
      - name: id
        description: "player id (hash of name and team)"
        tests:
          - not_null
      - name: nb_games
        description: "Number of games played on the season"
        tests:
          - not_null


sources:
  - name: local_source
    config:
      external_location: "./local_source/{name}.{extension}"
    tables:
      - name: game_boxscore_2024
        description: "A source table containing boxscore of every games for 2024 season"
        meta:
          extension: parquet

      - name: game_schedule_2024
        description: "A source table containing the schedule of every games for 2024 season"
        meta:
          extension: parquet


      - name: season_calendar
        description: "Start and end date of seasons"
        meta:
          extension: csv
