name: "Deploy doc"

on:
  push:
    branches:
      - 'main'
      - 'host-doc-github'  # TODO: switch with main once development finished
      - '*'

  pull_request:
    types: [opened, reopened, edited, assigned, unassigned]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout current branch"
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # added for test while developping only
      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff check -v .
        continue-on-error: false
